version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: securefiles-postgres
    restart: always
    environment:
      POSTGRES_DB: securefiles
      POSTGRES_USER: secureuser
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
