server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securefiles
    username: secureuser
    password: securepass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
